

### get game info 

//@games=9P8DL6W0JBB8,9P8DL6W0JBB8
@games=9MW7H0DVS9T6

GET /v7.0/products?bigIds={{games}}&market=US&languages=en-us&MS-CV=DGU1mcuYo0WMMp HTTP/1.1
Host: displaycatalog.mp.microsoft.com